name: screentime
description: "Screen Time Tracking and Management Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Theming
  fluent_ui: ^4.4.0
  adaptive_theme: ^3.6.0
  flutter_svg: ^2.0.17

  # Windows-specific Utilities
  bitsdojo_window: ^0.1.6
  launch_at_startup: ^0.3.1
  system_tray: ^2.0.3
  tray_manager: ^0.3.2
  windows_notification: ^1.3.0

  # Data Persistence and Preferences
  shared_preferences: ^2.5.2
  hive_flutter: ^1.1.0
  
  # Charts and Visualization
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.4
  pie_chart: ^5.4.0
  
  # Utility Packages
  package_info_plus: ^8.0.0
  intl: ^0.19.0
  ffi: ^2.1.4

  # Native Code Interaction for Foreground Window
  # You'll need to implement a custom plugin or package
  # Placeholder for your native window tracking plugin
  # native_window_tracker:
  #   path: path/to/your/local/plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/tray_icon.png
    # Add more assets as needed

# Platform-specific configuration
platforms:
  windows:
    pluginClass: ForegroundWindowPlugin